import { z } from "zod";

export const validateSampleUpload = z.object({
  label: z.string().min(1, "Label is required"),
  fe: z.string().optional(),
  pb: z.string().optional(),
  cu: z.string().optional(),
  sn: z.string().optional(),
  cr: z.string().optional(),
  al: z.string().optional(),
  ni: z.string().optional(),
  si: z.string().optional(),
  h2o: z.string().optional(),
  flash: z.string().optional(),
  soot_percent: z.string().optional(),
  b: z.string().optional(),
  na: z.string().optional(),
  v: z.string().optional(),
  li: z.string().optional(),
  ca: z.string().optional(),
  ba: z.string().optional(),
  zn: z.string().optional(),
  p: z.string().optional(),
  mg: z.string().optional(),
  mo: z.string().optional(),
  k: z.string().optional(),
  tbn: z.string().optional(),
  tan: z.string().optional(),
  v40: z.string().optional(),
  v100: z.string().optional(),
  paco_iso: z.string().optional(),
  paco_nas: z.string().optional(),
  oxp: z.string().optional(),
  nip: z.string().optional(),
  iph: z.string().optional(),
  appearence: z.string().optional(),
  acid_index: z.string().optional(),
  ag: z.string().optional(),
});

export type SampleUpload = z.infer<typeof validateSampleUpload>;
